Repository MovingBlocks/gestalt, pull requests merged in 2021-04, with the labels that each got.

#96 chore: upgrade gradle to 6.8.2 from 5.4.1
  build.gradle
  gestalt-android/build.gradle
  gestalt-asset-core/build.gradle
  gestalt-entity-system/build.gradle
  gestalt-es-perf/build.gradle
  gestalt-module/build.gradle
  gestalt-module/src/main/java/org/terasology/gestalt/module/sandbox/JavaModuleClassLoader.java
  gestalt-util/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  testpack/moduleA/build.gradle
  testpack/moduleB/build.gradle
  testpack/moduleC/build.gradle
  testpack/moduleD/build.gradle
  testpack/moduleF/build.gradle
Labels: v7

#97 test: upgrade tests to JUnit 5
  build.gradle
  gestalt-asset-core/build.gradle
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/AbstractFragmentProducerTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/AssetManagerTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/AssetTypeTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/ResourceUrnTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/module/AssetFileDataProducerTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/module/ModuleAwareAssetTypeManagerTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/module/ModuleDependencyResolutionStrategyTest.java
  gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/module/autoreload/ModuleEnvironmentWatcherTest.java
  gestalt-entity-system/build.gradle
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/component/management/ComponentManagerTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/component/management/ComponentTypeFactoryTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/component/management/ComponentTypeIndexTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/entity/FullSetupExample.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/event/EventProcessorTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/event/EventReceiverMethodSupportTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/event/EventSystemTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/prefab/PrefabInstantiationTest.java
  gestalt-entity-system/src/test/java/org/terasology/gestalt/entitysystem/prefab/PrefabJsonFormatTest.java
  gestalt-es-perf/build.gradle
  gestalt-es-perf/src/test/java/org/terasology/gestalt/entitysystem/component/management/perf/ComponentManagerTest.java
  gestalt-es-perf/src/test/java/org/terasology/gestalt/entitysystem/event/AbstractEventReceiverMethodSupportTest.java
  gestalt-module/build.gradle
  gestalt-module/src/test/java/org/terasology/gestalt/i18n/I18nMapTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/EmbeddedLibraryTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/ForceIncludeOptionalDependencyResolverTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/ModuleMetadataJsonAdapterTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/NormalDependencyResolverTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/PermissiveSandboxTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/SandboxTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/TableModuleRegistryTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/UseOptionalIfAvailableDependencyResolverTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/resources/BaseFileSourceTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/resources/ClasspathFileSourceTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/sandbox/APIScannerTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/naming/NameTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/naming/NameVersionTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/naming/VersionRangeTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/naming/VersionTest.java
  gestalt-util/build.gradle
  gestalt-util/src/test/java/org/terasology/gestalt/util/collection/KahnSorterTest.java
  gestalt-util/src/test/java/org/terasology/gestalt/util/io/FileExtensionPathMatcherTest.java
  gestalt-util/src/test/java/org/terasology/gestalt/util/reflection/ClassFactoryTest.java
  gestalt-util/src/test/java/org/terasology/gestalt/util/reflection/GenericsUtilTest.java
Labels: v7

#98 test: fix tests under java 11
  gestalt-module/src/test/java/org/terasology/gestalt/module/sandbox/APIScannerTest.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/sandbox/apipackage/ClassInApiPackage.java
  gestalt-module/src/test/java/org/terasology/gestalt/module/sandbox/apipackage/package-info.java
Labels: v7

#101 feat: use Semver compatibility for dependency info
  gestalt-module/src/main/java/org/terasology/gestalt/module/dependencyresolution/DependencyInfo.java
  gestalt-module/src/main/java/org/terasology/gestalt/module/dependencyresolution/DependencyResolver.java
  gestalt-module/src/main/java/org/terasology/gestalt/module/dependencyresolution/ResolutionAttempt.java
  gestalt-module/src/main/java/org/terasology/gestalt/naming/SemverExpression.java
  gestalt-module/src/main/java/org/terasology/gestalt/naming/Version.java
  gestalt-module/src/main/java/org/terasology/gestalt/naming/VersionRange.java
Labels: bug, gestalt-module, v7

#99 feat: add toString methods on some resolver classes
  gestalt-module/src/main/java/org/terasology/gestalt/module/dependencyresolution/ResolutionAttempt.java
Labels: enhancement, v7

#106 Release/v7.x logistics updates
  .gitignore
  Jenkinsfile
  build.gradle
  gestalt-android-testbed/build.gradle
  gestalt-android/build.gradle
  gestalt-asset-core/build.gradle
  gestalt-entity-system/build.gradle
  gestalt-es-perf/build.gradle
  gestalt-module/build.gradle
  gestalt-serialization/build.gradle
  gestalt-util/build.gradle
  gradle.properties
  gradle/common.gradle
  testpack/moduleA/build.gradle
  testpack/moduleB/build.gradle
  testpack/moduleC/build.gradle
  testpack/moduleD/build.gradle
  testpack/moduleF/build.gradle
  testpack/testpack-api/build.gradle
Labels: v7

#103 ci: add Jenkinsfile
  Jenkinsfile
Labels: v7

#110 build(gestalt-module): semver is part of the ABI
  gestalt-module/build.gradle
Labels: gestalt-module, v7
